## Multilevel Linear Regression Model

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
```

```{r load libraries}
if(!require('pacman')) install.packages('pacman')
pacman::p_load(
  readr,
  dplyr,
  broom,
  knitr,
  caret
)
```

```{r}
rate.df <- read_csv('../../data/rates_clean.csv', col_types = cols())

rate.fields <- c('neighbourhood_group_cleansed', 'neighbourhood_cleansed', 'property_type', 'room_type', 
                 'bedrooms', 'bathrooms', 'guests_included', 'lnprice')

rate.df$neighbourhood_group_cleansed <- as.factor(rate.df$neighbourhood_group_cleansed)
rate.df$neighbourhood_cleansed <- as.factor(rate.df$neighbourhood_cleansed)
rate.df$property_type <- as.factor(rate.df$property_type)
rate.df$room_type <- as.factor(rate.df$room_type)
rate.df$bedrooms <- as.integer(rate.df$bedrooms)
rate.df$bathrooms <- as.numeric(rate.df$bathrooms)
rate.df$guests_included <- as.integer(rate.df$guests_included)
rate.df$price <- as.numeric(rate.df$price)

rate.df$neighbourhood_group_cleansed <- relevel(rate.df$neighbourhood_group_cleansed, 'Manhattan')
rate.df$neighbourhood_cleansed <- relevel(rate.df$neighbourhood_cleansed, 'Harlem')
rate.df$property_type <- relevel(rate.df$property_type, 'Apartment')
rate.df$room_type <- relevel(rate.df$room_type, 'Entire home/apt')

set.seed(1)
train.index <- sample(c(1:dim(rate.df)[1]), dim(rate.df)[1]*0.7)
```

```{r}
rate.linr1 <- lm(lnprice ~ neighbourhood_group_cleansed + property_type + room_type + bedrooms + 
                   bathrooms + guests_included, 
                 data = rate.df, subset = train.index, na.action = na.exclude)
glance(rate.linr1) %>%
  dplyr::select(r.squared, adj.r.squared, AIC, BIC)
```

```{r}
rate.linr2 <- lm(lnprice ~ neighbourhood_cleansed + property_type + room_type + bedrooms + 
                   bathrooms  + guests_included, 
                 data = rate.df, subset = train.index, na.action = na.exclude)
glance(rate.linr2) %>%
  dplyr::select(r.squared, adj.r.squared, AIC, BIC)
```

```{r}
rate.linr3 <- step(lm(lnprice ~ 1, data = rate.df, subset = train.index, na.action = na.exclude),
                   scope = list(lower = lnprice ~ 1, upper = formula(rate.linr2)),
                   direction = 'forward', trace = 0,  k = log(nrow(rate.df[train.index, ])))
formula(rate.linr3)
```

```{r}
rate.linr4 <- step(rate.linr2, scope = list(lower = lnprice ~ 1, upper = formula(rate.linr2)),
                   direction = 'backward', trace = 0,  k = log(nrow(rate.df[train.index, ])))
formula(rate.linr4)
```

```{r}
rate.linr.pred.train <- predict(rate.linr2, na.action = na.pass)
data.frame(
  RMSE = RMSE(rate.linr.pred.train, rate.df[train.index, ]$lnprice),
  MAE = MAE(rate.linr.pred.train, rate.df[train.index, ]$lnprice),
  R2 = R2(rate.linr.pred.train, rate.df[train.index, ]$lnprice)
)
```

```{r}
rate.linr.pred.valid <- predict(rate.linr2, newdata = rate.df[-train.index, ], na.action = na.pass)
data.frame(
  RMSE = RMSE(rate.linr.pred.valid, rate.df[-train.index, ]$lnprice),
  MAE = MAE(rate.linr.pred.valid, rate.df[-train.index, ]$lnprice),
  R2 = R2(rate.linr.pred.valid, rate.df[-train.index, ]$lnprice)
)
```

```{r}
data.frame(rate.df[-train.index, !(names(rate.df) %in% c('price', 'lnprice'))], 
           actual_rate = rate.df[-train.index, ]$price, prediced_rate = round(exp(rate.linr.pred.valid), 2))
```